### ISSUE TITLE
stroop.py crashes

### ISSUE THREAD

**Issue by chrplr** [expyriment/expyriment-stash#9]
```
(base) chrplr:~/4_code/expyriment-stash/examples/fmri/stroop_task (master)$ python stroop_task.py 
Expyriment 0.10.0 (Python 3.7.7) 
Main file: stroop_task.py (e208b2)
Design plugins:
 StimulationProtocol
Traceback (most recent call last):
  File "/home/cp983411/anaconda3/lib/python3.7/site-packages/expyriment/design/_structure.py", line 1853, in get_factor
    rtn = self._factors[name]
KeyError: 'condition'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "stroop_task.py", line 67, in <module>
    exp.blocks[0] = in_protocol.get_as_experimental_block(block=exp.blocks[0])
  File "/home/cp983411/.expyriment/extras/expyriment_design_extras/stimulationprotocol/_stimulationprotocol.py", line 356, in get_as_experimental_block
    c2 = [t.get_factor("condition") in conditions for t in b.trials]
  File "/home/cp983411/.expyriment/extras/expyriment_design_extras/stimulationprotocol/_stimulationprotocol.py", line 356, in <listcomp>
    c2 = [t.get_factor("condition") in conditions for t in b.trials]
  File "/home/cp983411/anaconda3/lib/python3.7/site-packages/expyriment/design/_structure.py", line 1858, in get_factor
    raise RuntimeError(_FACTOR_NOT_EXIST.format(name))
RuntimeError: The factor 'condition' does not exist!
Use has_factor(name) to check if a factor is defined.
```

**Comment by fladd** [comment]
Should work now.
